
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlsvoff.connect;
import static qlsvoff.connect.dbPassword;
import static qlsvoff.connect.dbURL;
import static qlsvoff.connect.dbUser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class FStudent extends javax.swing.JFrame {

    /**
     * Creates new form FStudent
     */
    public FStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fStudent_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fAge = new javax.swing.JTextField();
        fSave = new javax.swing.JButton();
        fdelete = new javax.swing.JButton();
        fExit = new javax.swing.JButton();
        fRefesh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Student_ID");

        fStudent_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fStudent_IDActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel2.setText("Age");

        fSave.setText("Lưu Mới");
        fSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSaveActionPerformed(evt);
            }
        });

        fdelete.setText("Xóa");
        fdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdeleteActionPerformed(evt);
            }
        });

        fExit.setText("Thoát");
        fExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fExitActionPerformed(evt);
            }
        });

        fRefesh.setText("Refesh");

        fTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(fTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fStudent_ID))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(fAge))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(fdelete)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fRefesh))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fStudent_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSave)
                    .addComponent(fdelete)
                    .addComponent(fExit)
                    .addComponent(fRefesh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fStudent_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fStudent_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fStudent_IDActionPerformed

    private void fExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fExitActionPerformed

    private void fdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdeleteActionPerformed

    public void showdulieu() {
        try {
            fTable.removeAll();
            String[] arr = {"Student_ID", "NAME", "AGE"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            String query = "select *FROM dbo.[QLSVOFF]";
            Connection con = DriverManager.getConnection(dbURL,dbUser,dbPassword);
            Statement stmt = con.createStatement();
            preparedStatement ps = (preparedStatement) con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
            Vector vector= new Vector();
            vector.add(rs.getInt("Student_ID"));
            vector.add(rs.getString("NAME"));
            vector.add(rs.getInt("AGE"));
            model.addRow(vector);
        }
            fTable.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(FStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       showdulieu();
    }//GEN-LAST:event_formComponentShown

    private void checktrungid(){
        try {
            String query = "select *FROM dbo.[QLSVOFF] where Student_ID = ?";
            Connection con = DriverManager.getConnection(dbURL,dbUser,dbPassword);
            Statement stmt = con.createStatement();
            preparedStatement ps = (preparedStatement) con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                Vector vector= new Vector();
                vector.add(rs.getInt("Student_ID"));
                vector.add(rs.getString("NAME"));
                
            }   } catch (SQLException ex) {
            Logger.getLogger(FStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSaveActionPerformed
       if(fStudent_ID.getText().equals("")){
           JOptionPane.showMessageDialog(null, "ID sinh viên không được rỗng");
           fStudent_ID.requestFocus();
           return;
       }else if(fName.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Tên sinh viên không được rỗng"); 
           fName.requestFocus();
           return;
       }else if(fAge.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Tuổi sinh viên không được rỗng");
           fAge.requestFocus();
           return;
       }
       String id = fStudent_ID.getText();
       if(fStudent_ID.getText().length() !=4){
           JOptionPane.showMessageDialog(null, "ID sinh viên phải có 4 ký tự");
           fStudent_ID.requestFocus();
           return; 
       }else{
           boolean id1 = Character.isDigit(id.charAt(0));
           boolean id2 = Character.isDigit(id.charAt(1));
           boolean id3 = Character.isDigit(id.charAt(2));
           boolean id4 = Character.isDigit(id.charAt(3));
           if(id1 && id2 && id3 && id4 ){
            JOptionPane.showMessageDialog(null, "chuẩn");
           return;  }
       else {
           JOptionPane.showMessageDialog(null, "Mã Sinh viên phải là số!");
           return;
               }
       
    }//GEN-LAST:event_fSaveActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fAge;
    private javax.swing.JButton fExit;
    private javax.swing.JTextField fName;
    private javax.swing.JButton fRefesh;
    private javax.swing.JButton fSave;
    private javax.swing.JTextField fStudent_ID;
    private javax.swing.JTable fTable;
    private javax.swing.JButton fdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private static class jFrame {

        public jFrame() {
        }
    }
}
